### ISSUE TITLE
./test.sh not working

### ISSUE THREAD

**Issue by DhruvGamdha** [nagadomi/distro#1]
I followed the instructions.
1) cloned the repository to my Ubuntu 18.04 system.
2) cd ~/distro
3) bash install-deps
4) ./install.sh
5) ./update.sh
6) ./clean.sh
7) rm -rf ./install
8) Then I removed the "torch-activate" entry from .bashrc 
9) ./test.sh  

upto step 8, everything was working good. but in executing step 9, following error is showing.

![Selection_002](https://user-images.githubusercontent.com/21988638/64076110-0201f700-ccde-11e9-92ab-547411773c23.png)
 
Please Help.

**Comment by nagadomi** [comment]
step 6-8 is the instructions to uninstall torch7.
It does not have to run.
