### ISSUE TITLE
Install on Ubuntu20.04

### ISSUE THREAD

**Issue by track-ac** [nagadomi/distro#12]
Dear,
Thank you for your efforts.
I am trying to install this Torch on Ubuntu 20.04. But I have problems when I run 'bash install-deps'. 
The problems are that 'Package 'libqt4-dev' has no installation candidate' and 'Package 'ipython' has no installation candidate'
It seems that Ubuntu 20.04 removed **libqt4-dev** and **ipython**, 

I install  'libqt4-dev' with another ppa, however, I cannot find a suitable ppa for ipython on Ubuntu20.04.

Do you have any ideas?

Thank you.

**Comment by nagadomi** [comment]
I guess ipython is a package that only needs iTorch(IPython/Jupyter Notebooks kernel for Torch7). Also, iTorch is not installed by default, so ipython package might not be necessary.

**Comment by track-ac** [comment]
@nagadomi However, if I do not install the above two packages, then I cannot run `bash install-dep`. It will output the two packages have no installation candidate. Thus, I cannot install Torch in your repository.

**Comment by nagadomi** [comment]
I added `ubuntu20.04-ppa` branch.
It uses an unofficial PPA(Personal Package Archive) for qt4 ( https://launchpad.net/~rock-core/+archive/ubuntu/qt4/ ).
Unofficial packages can cause problems, so use at your own risk.

```
git clone https://github.com/nagadomi/distro.git -b ubuntu20.04-ppa ~/torch
./install-deps
./update.sh
```
I think it's better to compile `qt4.8` locally just like [install_openbals()](https://github.com/nagadomi/distro/blob/2dac858fccf28846e969ec8b202f106166fa27b7/install-deps#L9). But it seems like a lot of work. Pull requests are welcome.

**Comment by track-ac** [comment]
@nagadomi Thank you very much, your branch worked for me. But another thing needs attention.
Please make sure **the versions of gfortran, gcc and g++ are the same.** On Ubuntu20.04, when `./install-deps`, it will install gfortran version 9 that is not same with my gcc-7 g++-7 (because I use CUDA10.1 which dose not support gcc-9 ). 

Thank you again for your efforts.

**Comment by nagadomi** [comment]
I didn't notice the gcc version problem because I wrote the following line in zshrc:
```
export CC=gcc-8
export GXX=g++-8
```
But the problem has been around since before. #5
