### ISSUE TITLE
 Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by AlexHex7** [nagadomi/distro#2]
@nagadomi 
My setting is CUDA10.0 Cudnn 7.6.0
I follow your step https://github.com/torch/cutorch/issues/834#issuecomment-428767642
It says:
fatal: unable to access 'http://github.com/nagadomi/cutorch.git/': Recv failure: Connection reset by peer
fatal: clone of 'http://github.com/nagadomi/cutorch.git' into submodule path 'extra/cutorch' faile
( I use git clone to get cutorch to **extra/**.)

After that, I run my code. error comes up:  module 'cudnn' not found:No LuaRocks module found for cudnn.

Then I install cudnn by "luarocks install --only-from=https://luarocks.org/dev cudnn".  It saids that "Missing dependencies for cudnn: cutorch"

So download your repo "https://github.com/nagadomi/cutorch", "cd cutorch/; luarocks install rocks/cutorch-scm-1.rockspec". The error is:

> CMake Error at /usr/local/share/cmake-3.16/Modules/FindCUDA.cmake:707 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:7 (FIND_PACKAGE)

**Comment by nagadomi** [comment]
I've fixed cutorch URL https://github.com/nagadomi/distro/commit/2dac858fccf28846e969ec8b202f106166fa27b7 (http->https). Try again from git clone distro.
But it worked in my network environment. There may be a problem with your network.

**Comment by AlexHex7** [comment]
@nagadomi Thanks, It works. As for the  **CMake Error**, my cuda_path is wrong. So I change it.

And thanks again for provided this repo. It really helps me a lot.
