### ISSUE TITLE
How to install Lua52 version successfully?

### ISSUE THREAD

**Issue by Labyrins** [nagadomi/distro#8]
Hello!
I'm working on Ubuntu 18.04 
Even though Lua52 version was installed successfully.
But, test.sh showed it fail.

> Using Lua at:
> /home/ubuntu/torch/install/bin/lua
> paths loaded succesfully
> torch loaded succesfully
> ./test.sh: line 16: 28346 Segmentation fault      (core dumped) $LUA -ltorch -e "print('torch loaded succesfully')"

Also, every lua files brought out "Segmentation fault  (core dumped) "

How do I do?
I tried several times to resolve this issue.
Thanks in advance.

**Comment by nagadomi** [comment]
lua52 version seems not to work. Use luajit version or fix it yourself. I have not used it.

**Comment by Labyrins** [comment]
@nagadomi Thanks for your comment.
I gonna find other way to solve it.
